CREATE DATABASE IF NOT EXISTS docebo_test;

CREATE TABLE IF NOT EXISTS node_tree(
  idNode INT NOT NULL AUTO_INCREMENT,
  level INT NOT NULL,
  iLeft INT NOT NULL,
  iRight INT NOT NULL,
  PRIMARY KEY (idNode)
);

CREATE TABLE IF NOT EXISTS node_tree_names(
idName INT NOT NULL AUTO_INCREMENT,
  idNode INT NOT NULL,
  language VARCHAR(30) NOT NULL,
  nodeName VARCHAR(255) NOT NULL,
  PRIMARY KEY (idName),
  FOREIGN KEY (idNode) REFERENCES node_tree(idNode) ON DELETE CASCADE
);